# fly.toml app configuration file generated for getplutto-blog on 2024-04-04T19:08:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'getplutto-blog'
primary_region = 'sjc'

[build]
  [build.args]
    NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST = "blog.getplutto.com"

[env]
  NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST = "blog.getplutto.com"
  NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT = "https://gql.hashnode.com"
    NEXT_PUBLIC_PLUTTO_URL = "https://getplutto.com"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
